services:
  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiumbr
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/scripts/db.sql:/docker-entrypoint-initdb.d/db.sql #se agrego esta linea creacion tablas automaticamente
    ports:
      - "5433:5432"

  backend:
    build: ./Backend
    container_name: backend-api
    depends_on:
      - db
    env_file:
      - ./Backend/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "8081:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html

volumes:
  postgres_data:
